version: "3.8"
services:
  react_vite_docker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/srv/app
      - /srv/app/node_modules
    tty: true
