version: "3.8"
services:
  node:
    volumes:
      - .:/server:ro
      - /server/node_modules/bcrypt/
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # External port:Internal port
      - 5000:5000
    environment:
      - PORT=5000
      - MONGO_NODE_USERNAME=${MONGO_NODE_USERNAME}
      - MONGO_NODE_PASSWORD=${MONGO_NODE_PASSWORD}
    depends_on:
      - mongo

  python_nxtwatch:
    build:
      context: ./python/nxtwatch
      dockerfile: Dockerfile
    environment:
      - MONGO_NXTWATCH_USERNAME=${MONGO_NXTWATCH_USERNAME}
      - MONGO_NXTWATCH_PASSWORD=${MONGO_NXTWATCH_PASSWORD}
    ports:
      # External port:Internal port
      - 4000:5000
    volumes:
      - ./python/nxtwatch:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      # External port:Internal port
      - 27017:27017
    volumes:
      - mongoDB:/data/db

  redis:
    image: redis

volumes:
  mongoDB:
