import { WatchInfo } from "./WatchInfoModel";

export const SkeletonWatchInfo: WatchInfo = {
  _id: "",
  name: "",
  brand: "",
  notes: "",
  model_numbers: [],
  price: {
    msrp: "",
    authorized_dealer: "",
    grey_market: "",
    used: "",
  },
  main_color: "",
  secondary_colors: [],
  watch_style: "",
  water_resistance: "",
  rotating_bezel: "",
  material: "",
  bezel_insert_material: "",
  bezel_insert_color: "",
  crystal: "",
  movement: {
    type: "",
    name: "",
    power_reserve: "",
    frequency: "",
    jewels: "",
  },
  bracelet_strap: {
    type: "",
    material: "",
    color: "",
    clasp_quality: "",
    clasp_type: "",
    dive_extension: "",
  },
  date_window: "",
  day_window: "",
  dimensions: {
    diameter: "",
    lug_to_lug: "",
    thickness: "",
    lug_width: "",
  },
  links: {
    brand: "",
    authorized_dealers: [],
    grey_market: [],
    used: [],
  },
};
